clusterName: "rocketmq-helm" # 集群名称
nameOverride: rocketmq

image:
  repository: "apache/rocketmq"
  pullPolicy: IfNotPresent
  tag: "5.3.0" # 镜像版本

podSecurityContext:
  fsGroup: 3000
  runAsUser: 3000

broker:
  size:
    master: 2 # 主节点数量
    replica: 1 # 每个主节点的从节点数量
  # 2个 master 节点，每个 master 具有1个副节点，共4个 broker 节点 测试环境从节点可为0
  # podSecurityContext: {}
  # containerSecurityContext: {}
  
  master:
    brokerRole: ASYNC_MASTER # 主节点角色 ASYNC_MASTER（异步主机）无延迟、SYNC_MASTER（同步主机）有延迟
    jvm:
      maxHeapSize: 2048M
      # javaOptsOverride: ""
    resources:
      limits:
        cpu: 4
        memory: 16Gi
      requests:
        cpu: 200m
        memory: 3Gi
  
  replica:
    jvm:
      maxHeapSize: 1300M
      # javaOptsOverride: ""
    resources:
      limits:
        cpu: 4
        memory: 16Gi
      requests:
        cpu: 50m
        memory: 2Gi

  hostNetwork: false

  persistence:
    enabled: true
    size: 20Gi
    #storageClass: "" # 存储类型
  
  aclConfigMapEnabled: false # 是否启用 ACL 配置
  aclConfig: |
    globalWhiteRemoteAddresses:
      - '*'
      - 10.*.*.*
      - 192.168.*.*

  config:
    ## brokerClusterName brokerName brokerRole brokerId 由内置脚本自动生成
    deleteWhen: "04"
    fileReservedTime: "48"
    flushDiskType: "ASYNC_FLUSH"
    waitTimeMillsInSendQueue: "1000"
    # aclEnable: true

  affinityOverride: {}
  tolerations: []
  nodeSelector: {}

  ## broker.readinessProbe
  readinessProbe:
    tcpSocket:
      port: main
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 6

nameserver:
  replicaCount: 3

  jvm:
    maxHeapSize: 600M
    # javaOptsOverride: ""

  resources:
    limits:
      cpu: 2
      memory: 6Gi
      ephemeral-storage: 8Gi
    requests:
      cpu: 100m
      memory: 1Gi
      ephemeral-storage: 1Gi
  
  persistence:
    enabled: false
    size: 20Gi
    #storageClass: "" # 存储类型

  affinityOverride: {}
  tolerations: []
  nodeSelector: {}

  ## nameserver.readinessProbe
  readinessProbe:
    tcpSocket:
      port: main
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 6

  ## nameserver.service
  service:
    annotations: {}
    type: ClusterIP

proxy:
  enabled: true
  replicaCount: 2
  jvm:
    maxHeapSize: 1300M
    # javaOptsOverride: ""

  resources:
    limits:
      cpu: 2
      memory: 6Gi
    requests:
      cpu: 100m
      memory: 2Gi

  affinityOverride: {}
  tolerations: []
  nodeSelector: {}

  ## proxy.readinessProbe
  readinessProbe:
    tcpSocket:
      port: main
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 6

  ## proxy.service
  service:
    annotations: {}
    type: ClusterIP

dashboard:
  enabled: true
  replicaCount: 1
  image:
    repository: "apacherocketmq/rocketmq-dashboard"
    pullPolicy: IfNotPresent
    tag: "1.0.0" # 镜像版本

  auth:
    enabled: true # 是否启用认证
    users:
      - name: admin
        password: admin # 管理员密码
        isAdmin: true
      - name: user01
        password: userPass # 用户密码

  jvm:
    maxHeapSize: 600M # JVM 堆内存大小

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 20m
      memory: 1Gi

  ## dashboard.readinessProbe
  readinessProbe:
    failureThreshold: 6
    httpGet:
      path: /
      port: http
  livenessProbe: {}
  
  service:
    annotations: {}
    type: ClusterIP
    # nodePort: 31007
  
  ingress:
    enabled: false
    className: ""
    annotations: {}
      # nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,124.160.30.50
    hosts:
      - host: rocketmq-dashboard.example.com
    tls: []
    #  - secretName: example-tls
    #    hosts:
    #      - rocketmq-dashboard.example.com

## controller mode is an experimental feature
controllerModeEnabled: false # 是否启用 controller 模式
controller:
  enabled: false # 是否启用 controller
  replicaCount: 3
  jvm:
    maxHeapSize: 600M
    # javaOptsOverride: ""
  resources:
    limits:
      cpu: 2
      memory: 6Gi
    requests:
      cpu: 100m
      memory: 1Gi
  persistence:
    enabled: true
    size: 20Gi
    accessModes:
      - ReadWriteOnce
  
  ## controller.service
  service:
    annotations: {}
  
  ## controller.config
  config:
    controllerDLegerGroup: group1
    enableElectUncleanMaster: false
    notifyBrokerRoleChanged: true
  
  ## controller.readinessProbe
  readinessProbe:
    tcpSocket:
      port: main
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 6

exporter:
  enabled: true
  replicaCount: 1
  image:
    repository: "apache/rocketmq-exporter"
    pullPolicy: IfNotPresent
    tag: "latest"
  
  # Exporter 配置
  config:
    namesrvAddr: ""  # 默认使用集群内部 nameserver
    rocketmqVersion: "rocketmq.config.rocketmqVersion:V5_3_0" # rocketmq 版本 注：需要和 rocketmq 版本一致 否则会有部分指标不显示
    
  # 环境变量配置
  env: []

  
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  
  service:
    type: ClusterIP
    port: 5557
    annotations: {}
  
  # Prometheus ServiceMonitor 配置
  serviceMonitor:
    enabled: false 
    interval: 30s
    env: "prod"
    # cluster: 默认使用 .Values.clusterName 的值
    additionalLabels: {}
    
  # 健康检查配置
  livenessProbe:
    httpGet:
      path: /metrics
      port: metrics
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    
  readinessProbe:
    httpGet:
      path: /metrics
      port: metrics
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  # Pod 调度配置
  affinity: {}
  tolerations: []
  nodeSelector: {}
  
  # 安全上下文配置
  podSecurityContext: {}
  containerSecurityContext: {}